baseURL = ""
languageCode = "en-us"
title = "EZ Game Art"

[params]
    dateFormat = "Jan 2, 2006"

[taxonomies]
    category = "categories"
    author = "authors"
    tag = ""
    includes = "includes"
